on:
  push:
    branches:
    - main
  workflow_dispatch:
  
permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: start deployment
      uses: bobheadxi/deployments@v1
      id: deployment
      with:
        step: start
        token: ${{ secrets.TOKEN }}
        env: release
        repository: jwenz723/testing-deployments2
        payload: '{"SHA":"${{ github.sha }}","run_id":"${{ github.run_id }}"}'

    - name: do my deploy
      run: sleep 5

    - name: update deployment status
      uses: bobheadxi/deployments@v1
      if: always()
      with:
        step: finish
        token: ${{ secrets.TOKEN }}
        status: ${{ job.status }}
        env: ${{ steps.deployment.outputs.env }}
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}
        repository: jwenz723/testing-deployments2
        env_url: https://google.com
